# Конфигурация для тестового окружения
services:
    _defaults:
        autowire: true

    # Делаем сервисы публичными для функциональных тестов
    App\Identity\Domain\Factory\UserFactory:
        public: true

    App\Identity\Infrastructure\Repository\DoctrineUserRepository:
        public: true

    App\Tests\Resource\Fixture\:
        resource: "%kernel.project_dir%/tests/Resource/Fixture/*"
        tags:
            - { "name": "doctrine.fixture.orm" }

    App\Shared\Infrastructure\Bus\CommandBus:
        public: true

    App\Shared\Infrastructure\Bus\QueryBus:
        public: true

